### ISSUE TITLE
Adding Twitter Wall to Homescreen

### ISSUE THREAD

**Issue by GeekBoySupreme** [GeekBoySupreme/dscomg#9]
Adding a wall to reflect the stream of Tweets about the event.
Similar to this.

<img width="758" alt="Screenshot 2020-06-14 at 9 09 39 PM" src="https://user-images.githubusercontent.com/15321738/84597714-7f6cb180-ae83-11ea-9b49-71faea393e2b.png">

**Comment by ashfaqnisar** [comment]
Hey @GeekBoySupreme, go ahead and close this issue 
PR: https://github.com/GeekBoySupreme/dscomg/pull/18
